In [ ]:
import pandas as pd
data=pd.read_excel("/content/employee.xxsl.xlsx")
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,NaN,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data.isnull()

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,True,False
3,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False
8,False,True,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Employee_ID      1
  Name           1
   Age           2
 Gender          1
Department       0
  Salary         0
   CIty          1
Joining -date    0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(6)

In [ ]:
data.columns=data.columns.str.strip()
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,NaN,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data['CIty']=data['CIty'].fillna('Mangaluru')
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data['Age']=data['Age'].fillna(56)
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data['Salary']=data['Salary'].fillna(25000)
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data['Employee_ID']=data['Employee_ID'].fillna(data['Employee_ID'].mode()[0])
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data.isnull().sum()

Employee_ID      0
Name             1
Age              0
Gender           1
Department       0
Salary           0
CIty             0
Joining -date    0
dtype: int64

In [ ]:
data['Name']=data['Name'].ffill()
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data.isnull().sum()
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data['Gender']=data['Gender'].bfill()
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data.isnull().sum()

Employee_ID      0
Name             0
Age              0
Gender           0
Department       0
Salary           0
CIty             0
Joining -date    0
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data['Name']=data['Name'].str.strip()
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data['CIty']=data['CIty'].str.strip()
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
data.duplicated().sum()
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
df=data.drop_duplicates()
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
df['CIty']=df['CIty'].str.strip()
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
df.drop('Joining -date',axis=1)

  Employee_ID     Name    Age  Gender Department  Salary       CIty
0      E101      Akash   25.0       M         IT   45000  Bengaluru
1        E102    Megha   56.0       F         HR   38000     Chenni
2        E103     John   28.0    Male    Finance   55000  Mangaluru
3      E101      Kavya  240.0  Female         IT   48000     Mysuru
4        E105   Darshi   26.0    Male      Sales   25000  Bengaluru
5        E106  Supriya   56.0  Female         HR  -38000     Chenni
6        E107   Darshi   26.0    Male      Sales   25000  Bengaluru
7        E108    Sneha   23.0  Female         IT   47000      Delhi
8        E109    Sneha  -27.0  Female    Finance   52000   Hydrabad
9        E110    Vikas   22.0    Male         IT   99999     Chenni

In [ ]:
import numpy as np
df.loc[df['Age']>90,'Age']=np.nan
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,NaN,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
df.loc[df['Salary']>100000,'Salary']=np.nan
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000.0,Bengaluru,2023-01-12
1,E102,Megha,56.0,F,HR,38000.0,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000.0,Mangaluru,2023-05-10
3,E101,Kavya,NaN,Female,IT,48000.0,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000.0,Bengaluru,2021-06-10
5,E106,Supriya,56.0,Female,HR,-38000.0,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000.0,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000.0,Delhi,2023-02-01
8,E109,Sneha,-27.0,Female,Finance,52000.0,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999.0,Chenni,2024-01-05

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.000000,M,IT,45000.0,Bengaluru,2023-01-12
1,E102,Megha,56.000000,F,HR,38000.0,Chenni,2022-02-15
2,E103,John,28.000000,Male,Finance,55000.0,Mangaluru,2023-05-10
3,E101,Kavya,26.111111,Female,IT,48000.0,Mysuru,2023-03-20
4,E105,Darshi,26.000000,Male,Sales,25000.0,Bengaluru,2021-06-10
5,E106,Supriya,56.000000,Female,HR,-38000.0,Chenni,2022-02-15
6,E107,Darshi,26.000000,Male,Sales,25000.0,Bengaluru,2021-06-10
7,E108,Sneha,23.000000,Female,IT,47000.0,Delhi,2023-02-01
8,E109,Sneha,-27.000000,Female,Finance,52000.0,Hydrabad,2022-08-22
9,E110,Vikas,22.000000,Male,IT,99999.0,Chenni,2024-01-05

In [ ]:
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.000000,M,IT,45000.0,Bengaluru,2023-01-12
1,E102,Megha,56.000000,F,HR,38000.0,Chenni,2022-02-15
2,E103,John,28.000000,Male,Finance,55000.0,Mangaluru,2023-05-10
3,E101,Kavya,26.111111,Female,IT,48000.0,Mysuru,2023-03-20
4,E105,Darshi,26.000000,Male,Sales,25000.0,Bengaluru,2021-06-10
5,E106,Supriya,56.000000,Female,HR,-38000.0,Chenni,2022-02-15
6,E107,Darshi,26.000000,Male,Sales,25000.0,Bengaluru,2021-06-10
7,E108,Sneha,23.000000,Female,IT,47000.0,Delhi,2023-02-01
8,E109,Sneha,-27.000000,Female,Finance,52000.0,Hydrabad,2022-08-22
9,E110,Vikas,22.000000,Male,IT,99999.0,Chenni,2024-01-05

In [ ]:
df.dtypes

Employee_ID              object
Name                     object
Age                     float64
Gender                   object
Department               object
Salary                  float64
CIty                     object
Joining -date    datetime64[ns]
dtype: object

In [ ]:
df['Age']=df['Age'].astype(int)
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25,M,IT,45000.0,Bengaluru,2023-01-12
1,E102,Megha,56,F,HR,38000.0,Chenni,2022-02-15
2,E103,John,28,Male,Finance,55000.0,Mangaluru,2023-05-10
3,E101,Kavya,26,Female,IT,48000.0,Mysuru,2023-03-20
4,E105,Darshi,26,Male,Sales,25000.0,Bengaluru,2021-06-10
5,E106,Supriya,56,Female,HR,-38000.0,Chenni,2022-02-15
6,E107,Darshi,26,Male,Sales,25000.0,Bengaluru,2021-06-10
7,E108,Sneha,23,Female,IT,47000.0,Delhi,2023-02-01
8,E109,Sneha,-27,Female,Finance,52000.0,Hydrabad,2022-08-22
9,E110,Vikas,22,Male,IT,99999.0,Chenni,2024-01-05

In [ ]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'Salary', 'CIty',
       'Joining -date'],
      dtype='object')

In [ ]:
df['Salary']=df['Salary'].astype(int)
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56,F,HR,38000,Chenni,2022-02-15
2,E103,John,28,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,26,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22,Male,IT,99999,Chenni,2024-01-05

In [ ]:
df['Gender']=df['Gender'].replace({"M": "Male","F":"Female"})
df

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25,Male,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,56,Female,HR,38000,Chenni,2022-02-15
2,E103,John,28,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,26,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,56,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23,Female,IT,47000,Delhi,2023-02-01
8,E109,Sneha,-27,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22,Male,IT,99999,Chenni,2024-01-05

In [ ]:
df=pd.get_dummies(df,columns=['Gender'],dtype=int)
df

,Employee_ID,Name,Age,Department,Salary,CIty,Joining -date,Gender_Female,Gender_Male
0,E101,Akash,25,IT,45000,Bengaluru,2023-01-12,0,1
1,E102,Megha,56,HR,38000,Chenni,2022-02-15,1,0
2,E103,John,28,Finance,55000,Mangaluru,2023-05-10,0,1
3,E101,Kavya,26,IT,48000,Mysuru,2023-03-20,1,0
4,E105,Darshi,26,Sales,25000,Bengaluru,2021-06-10,0,1
5,E106,Supriya,56,HR,-38000,Chenni,2022-02-15,1,0
6,E107,Darshi,26,Sales,25000,Bengaluru,2021-06-10,0,1
7,E108,Sneha,23,IT,47000,Delhi,2023-02-01,1,0
8,E109,Sneha,-27,Finance,52000,Hydrabad,2022-08-22,1,0
9,E110,Vikas,22,IT,99999,Chenni,2024-01-05,0,1

In [ ]:
import pandas as pd
data=pd.read_excel("/content/Studentdata.excel.xlsx")
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00
2,S202,Priya,NaN,Female,BBA,78,Chennai,2023-07-15 00:00:00
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00
5,S205,Kiran,150,Male,BBA,65,Bengaluru,2023-07-10 00:00:00
6,S206,Anjali,22,Female,BCA,-45,Chennai,2023-07-15 00:00:00
7,NaN,Ravi,21,M,MCA,95,Delhi,2023-08-01 00:00:00
8,S208,NaN,20,Female,BCA,72,Hyderabad,2023-08-22 00:00:00
9,S209,Manju,-19,F,BBA,80,Bengaluru,2023-07-10 00:00:00
10,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05 00:00:00
11,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00
13,S213,Naveen,22,Male,BCA,NaN,Hyderabad,2023-08-25 00:00:00
14,S214,Pooja,20,Female,BBA,68,NaN,2023-07-12 00:00:00
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  15 non-null     object
 1   Unnamed: 1  15 non-null     object
 2   Unnamed: 2  15 non-null     object
 3   Unnamed: 3  16 non-null     object
 4   Unnamed: 4  15 non-null     object
 5   Unnamed: 5  15 non-null     object
 6   Unnamed: 6  15 non-null     object
 7   Unnamed: 7  16 non-null     object
dtypes: object(8)
memory usage: 1.1+ KB

In [ ]:
data.dtypes

Unnamed: 0    object
Unnamed: 1    object
Unnamed: 2    object
Unnamed: 3    object
Unnamed: 4    object
Unnamed: 5    object
Unnamed: 6    object
Unnamed: 7    object
dtype: object

In [ ]:
data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00
2,S202,Priya,NaN,Female,BBA,78,Chennai,2023-07-15 00:00:00
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00

In [ ]:
data.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
11,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00
13,S213,Naveen,22,Male,BCA,NaN,Hyderabad,2023-08-25 00:00:00
14,S214,Pooja,20,Female,BBA,68,NaN,2023-07-12 00:00:00
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00

In [ ]:
data.isnull()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,True,False,False,False,False,False,False,False
8,False,True,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False
13,False,False,False,False,False,True,False,False
14,False,False,False,False,False,False,True,False
15,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Unnamed: 0    1
Unnamed: 1    1
Unnamed: 2    1
Unnamed: 3    0
Unnamed: 4    1
Unnamed: 5    1
Unnamed: 6    1
Unnamed: 7    0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(6)

In [ ]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(1)

In [ ]:
data.drop_duplicates()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00
2,S202,Priya,NaN,Female,BBA,78,Chennai,2023-07-15 00:00:00
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00
5,S205,Kiran,150,Male,BBA,65,Bengaluru,2023-07-10 00:00:00
6,S206,Anjali,22,Female,BCA,-45,Chennai,2023-07-15 00:00:00
7,NaN,Ravi,21,M,MCA,95,Delhi,2023-08-01 00:00:00
8,S208,NaN,20,Female,BCA,72,Hyderabad,2023-08-22 00:00:00
9,S209,Manju,-19,F,BBA,80,Bengaluru,2023-07-10 00:00:00
10,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05 00:00:00
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00
13,S213,Naveen,22,Male,BCA,NaN,Hyderabad,2023-08-25 00:00:00
14,S214,Pooja,20,Female,BBA,68,NaN,2023-07-12 00:00:00
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00

In [ ]:
data.columns=data.columns.str.strip()
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00
2,S202,Priya,NaN,Female,BBA,78,Chennai,2023-07-15 00:00:00
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00
5,S205,Kiran,150,Male,BBA,65,Bengaluru,2023-07-10 00:00:00
6,S206,Anjali,22,Female,BCA,-45,Chennai,2023-07-15 00:00:00
7,NaN,Ravi,21,M,MCA,95,Delhi,2023-08-01 00:00:00
8,S208,NaN,20,Female,BCA,72,Hyderabad,2023-08-22 00:00:00
9,S209,Manju,-19,F,BBA,80,Bengaluru,2023-07-10 00:00:00
10,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05 00:00:00
11,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00
13,S213,Naveen,22,Male,BCA,NaN,Hyderabad,2023-08-25 00:00:00
14,S214,Pooja,20,Female,BBA,68,NaN,2023-07-12 00:00:00
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00

In [ ]:

data['Unnamed: 0'] = data['Unnamed: 0'].fillna('S207')
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Student_ID
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date,Student_ID
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
2,S202,Priya,NaN,Female,BBA,78,Chennai,2023-07-15 00:00:00,S202
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00,S203
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00,S204
5,S205,Kiran,150,Male,BBA,65,Bengaluru,2023-07-10 00:00:00,S205
6,S206,Anjali,22,Female,BCA,-45,Chennai,2023-07-15 00:00:00,S206
7,S207,Ravi,21,M,MCA,95,Delhi,2023-08-01 00:00:00,S207
8,S208,NaN,20,Female,BCA,72,Hyderabad,2023-08-22 00:00:00,S208
9,S209,Manju,-19,F,BBA,80,Bengaluru,2023-07-10 00:00:00,S209
10,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05 00:00:00,S210
11,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00,S212
13,S213,Naveen,22,Male,BCA,NaN,Hyderabad,2023-08-25 00:00:00,S213
14,S214,Pooja,20,Female,BBA,68,NaN,2023-07-12 00:00:00,S214
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00,S215

In [ ]:
data['Unnamed: 2']=data['Unnamed: 2'].fillna('45')
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Student_ID
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date,Student_ID
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
2,S202,Priya,45,Female,BBA,78,Chennai,2023-07-15 00:00:00,S202
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00,S203
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00,S204
5,S205,Kiran,150,Male,BBA,65,Bengaluru,2023-07-10 00:00:00,S205
6,S206,Anjali,22,Female,BCA,-45,Chennai,2023-07-15 00:00:00,S206
7,S207,Ravi,21,M,MCA,95,Delhi,2023-08-01 00:00:00,S207
8,S208,NaN,20,Female,BCA,72,Hyderabad,2023-08-22 00:00:00,S208
9,S209,Manju,-19,F,BBA,80,Bengaluru,2023-07-10 00:00:00,S209
10,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05 00:00:00,S210
11,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00,S212
13,S213,Naveen,22,Male,BCA,NaN,Hyderabad,2023-08-25 00:00:00,S213
14,S214,Pooja,20,Female,BBA,68,NaN,2023-07-12 00:00:00,S214
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00,S215

In [ ]:
data['Unnamed: 5']=data['Unnamed: 5'].fillna('124')
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Student_ID
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date,Student_ID
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
2,S202,Priya,45,Female,BBA,78,Chennai,2023-07-15 00:00:00,S202
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00,S203
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00,S204
5,S205,Kiran,150,Male,BBA,65,Bengaluru,2023-07-10 00:00:00,S205
6,S206,Anjali,22,Female,BCA,-45,Chennai,2023-07-15 00:00:00,S206
7,S207,Ravi,21,M,MCA,95,Delhi,2023-08-01 00:00:00,S207
8,S208,NaN,20,Female,BCA,72,Hyderabad,2023-08-22 00:00:00,S208
9,S209,Manju,-19,F,BBA,80,Bengaluru,2023-07-10 00:00:00,S209
10,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05 00:00:00,S210
11,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00,S212
13,S213,Naveen,22,Male,BCA,124,Hyderabad,2023-08-25 00:00:00,S213
14,S214,Pooja,20,Female,BBA,68,NaN,2023-07-12 00:00:00,S214
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00,S215

In [ ]:
data['Unnamed: 6']=data['Unnamed: 6'].fillna('Gadag')
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Student_ID
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date,Student_ID
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
2,S202,Priya,45,Female,BBA,78,Chennai,2023-07-15 00:00:00,S202
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00,S203
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00,S204
5,S205,Kiran,150,Male,BBA,65,Bengaluru,2023-07-10 00:00:00,S205
6,S206,Anjali,22,Female,BCA,-45,Chennai,2023-07-15 00:00:00,S206
7,S207,Ravi,21,M,MCA,95,Delhi,2023-08-01 00:00:00,S207
8,S208,NaN,20,Female,BCA,72,Hyderabad,2023-08-22 00:00:00,S208
9,S209,Manju,-19,F,BBA,80,Bengaluru,2023-07-10 00:00:00,S209
10,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05 00:00:00,S210
11,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00,S212
13,S213,Naveen,22,Male,BCA,124,Hyderabad,2023-08-25 00:00:00,S213
14,S214,Pooja,20,Female,BBA,68,Gadag,2023-07-12 00:00:00,S214
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00,S215

In [ ]:
data['Unnamed: 6']=data['Unnamed: 6'].str.strip()
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Student_ID
0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date,Student_ID
1,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
2,S202,Priya,45,Female,BBA,78,Chennai,2023-07-15 00:00:00,S202
3,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10 00:00:00,S203
4,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20 00:00:00,S204
5,S205,Kiran,150,Male,BBA,65,Bengaluru,2023-07-10 00:00:00,S205
6,S206,Anjali,22,Female,BCA,-45,Chennai,2023-07-15 00:00:00,S206
7,S207,Ravi,21,M,MCA,95,Delhi,2023-08-01 00:00:00,S207
8,S208,NaN,20,Female,BCA,72,Hyderabad,2023-08-22 00:00:00,S208
9,S209,Manju,-19,F,BBA,80,Bengaluru,2023-07-10 00:00:00,S209
10,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05 00:00:00,S210
11,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12 00:00:00,S201
12,S212,Divya,21,Female,NaN,76,Mysuru,2023-07-18 00:00:00,S212
13,S213,Naveen,22,Male,BCA,124,Hyderabad,2023-08-25 00:00:00,S213
14,S214,Pooja,20,Female,BBA,68,NaN,2023-07-12 00:00:00,S214
15,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30 00:00:00,S215

In [ ]:
data['Unnamed: 4'].unique()

array(['Course', 'BCA', 'BBA', 'MCA', '  BCA', nan], dtype=object)

In [ ]:
data['Unnamed: 4'].value_counts()

Unnamed: 4
BCA       5
MCA       4
BBA       4
Course    1
  BCA     1
Name: count, dtype: int64

In [ ]:
data['Unnamed: 5'].mean

<bound method Series.mean of 0     Marks
1        85
2        78
3        92
4        88
5        65
6       -45
7        95
8        72
9        80
10       89
11       85
12       76
13      124
14       68
15      105
Name: Unnamed: 5, dtype: object>

In [ ]:
data['Unnamed: 5'].median

<bound method Series.median of 0     Marks
1        85
2        78
3        92
4        88
5        65
6       -45
7        95
8        72
9        80
10       89
11       85
12       76
13      124
14       68
15      105
Name: Unnamed: 5, dtype: object>

In [ ]:
data.describe()

,Unnamed: 3_ Female,Unnamed: 3_F,Unnamed: 3_Female,Unnamed: 3_Gender,Unnamed: 3_M,Unnamed: 3_Male
count,16.0000,16.000000,16.000000,16.0000,16.000000,16.000000
mean,0.0625,0.125000,0.250000,0.0625,0.187500,0.312500
std,0.2500,0.341565,0.447214,0.2500,0.403113,0.478714
min,0.0000,0.000000,0.000000,0.0000,0.000000,0.000000
25%,0.0000,0.000000,0.000000,0.0000,0.000000,0.000000
50%,0.0000,0.000000,0.000000,0.0000,0.000000,0.000000
75%,0.0000,0.000000,0.250000,0.0000,0.000000,1.000000
max,1.0000,1.000000,1.000000,1.0000,1.000000,1.000000

In [ ]:
data.shape

(16, 14)