In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.3

In [ ]:
import pandas as pd
kavita=pd.Series([1,2,3,4,5])
kavita

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
import pandas as pd
marks=pd.Series([85,90,75,95])
print(marks)

0    85
1    90
2    75
3    95
dtype: int64

In [ ]:
import pandas as pd #list to series
arr=pd.Series([10,20,30,40])
print(arr[1:4])

1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
num=pd.Series([10,20,30,40,50])
print(num[0])

10

In [ ]:
import pandas as pd
student={'Rahul': 85,
         'Anita': 45,
          'Anu': 50,
          'kavya': 22}
s=pd.Series(student)

In [ ]:
import pandas as pd
student={'Name':"Anita",
         'Reg_No':132,
         'Place':"Gadag",
         'Year':2026,
         'Result':"Pass"
         }
student
demo=pd.Series(student)
demo
print(demo[1])
print(demo['Result'])
print(demo['Year'])
print(demo[-2])

132
Pass
2026
2026

/tmp/ipykernel_2967/3200373423.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[1])
/tmp/ipykernel_2967/3200373423.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[-2])

In [ ]:
import pandas as pd
arr=[86,45,89,34,67,88,94,12]
data=pd.Series(arr)
data
print(data[data>82])

0    86
2    89
5    88
6    94
dtype: int64

In [ ]:
import pandas as pd
marks=[80,90,100]
arr=pd.Series(marks)
print(arr * 2)

0    160
1    180
2    200
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
arr=np.array([80,90,95])
arr +=5
arr
new=pd.Series(arr)
new
print(new*2)
print(new[new>80])
print(new.dtype)
print(new.shape)
print(new.size)
print(new.index)
print(new.values)

0    170
1    190
2    200
dtype: int64
0     85
1     95
2    100
dtype: int64
int64
(3,)
3
RangeIndex(start=0, stop=3, step=1)
[ 85  95 100]

In [ ]:
# Dataframe programs
#1) Dict to DataFrame
import pandas as pd
demo={'Reg No':[11,12,13,14,15,18],
      'Name':['Anushri','Kerthi','pruthvi','Sagar','Akhil','Shivu'],
      'Age':[34,29,26,33,22,20],
      'Place':['Gadag','Belgav','Bagalkote','Haveri','Hasan','Badami']
      }
print(demo)
data=pd.DataFrame(demo)
data

{'Reg No': [11, 12, 13, 14, 15, 18], 'Name': ['Anushri', 'Kerthi', 'pruthvi', 'Sagar', 'Akhil', 'Shivu'], 'Age': [34, 29, 26, 33, 22, 20], 'Place': ['Gadag', 'Belgav', 'Bagalkote', 'Haveri', 'Hasan', 'Badami']}

   Reg No     Name  Age      Place
0      11  Anushri   34      Gadag
1      12   Kerthi   29     Belgav
2      13  pruthvi   26  Bagalkote
3      14    Sagar   33     Haveri
4      15    Akhil   22      Hasan
5      18    Shivu   20     Badami

In [ ]:
#csv file to DataFrame
import pandas as pd
data=pd.read_csv("/content/Employeee.csv")
data

   Emp id     Name  Salary Company
0     128    Madhu   25000     Tcs
1     112  Anupama   20000   Wipro
2     342   Adarsh   22000   Cisco
3      80    surya   21000  Ifosys

In [ ]:
import pandas as pd
data=pd.read_excel("/content/Teachers.xxsx.xlsx")

In [ ]:
print(data['Name'])

0      Madhu
1    Anupama
2     Adarsh
3      surya
Name: Name, dtype: object

In [ ]:
print(data['Salary'])

0    25000
1    20000
2    22000
3    21000
Name: Salary, dtype: int64

In [ ]:
print(data['Company'])

0       Tcs
1     Wipro
2     Cisco
3    Ifosys
Name: Company, dtype: object

In [ ]:
print(data['Emp id'])

0    128
1    112
2    342
3     80
Name: Emp id, dtype: int64

In [ ]:
print(data[['Name','Emp id']])

      Name  Emp id
0    Madhu     128
1  Anupama     112
2   Adarsh     342
3    surya      80

In [ ]:
(data[['Company','Salary']])

  Company  Salary
0     Tcs   25000
1   Wipro   20000
2   Cisco   22000
3  Ifosys   21000

In [ ]:
data['Age']=[20,22,18,19]
data.to_csv('Age',index=False)
data

   Emp id     Name  Salary Company  Age
0     128    Madhu   25000     Tcs   20
1     112  Anupama   20000   Wipro   22
2     342   Adarsh   22000   Cisco   18
3      80    surya   21000  Ifosys   19

In [ ]:
data['City']=['Gadag','Dharawad','Davanageri','Harihar']
data.to_csv('City',index=False)
data

   Emp id     Name  Salary Company  Age        City
0     128    Madhu   25000     Tcs   20       Gadag
1     112  Anupama   20000   Wipro   22    Dharawad
2     342   Adarsh   22000   Cisco   18  Davanageri
3      80    surya   21000  Ifosys   19     Harihar

In [ ]:
data=data.drop('Age',axis=1)
data

   Emp id     Name  Salary Company        City
0     128    Madhu   25000     Tcs       Gadag
1     112  Anupama   20000   Wipro    Dharawad
2     342   Adarsh   22000   Cisco  Davanageri
3      80    surya   21000  Ifosys     Harihar

In [ ]:
data=data.drop('City',axis=1)
data

   Emp id     Name  Salary Company
0     128    Madhu   25000     Tcs
1     112  Anupama   20000   Wipro
2     342   Adarsh   22000   Cisco
3      80    surya   21000  Ifosys

In [ ]:
print(data.columns)

Index(['    ID', '  Name', 'Department', '  Salary'], dtype='object')

In [ ]:
print(data.shape)

(4, 4)

In [ ]:
print(data.dtypes)

    ID         int64
  Name        object
Department    object
  Salary       int64
dtype: object

In [ ]:
print(data.index)

RangeIndex(start=0, stop=4, step=1)

In [ ]:
data.head()

       ID   Name  Department    Salary
0     101  Rahul          IT     50000
1     102  Anita          HR     40000
2     103   Raju       Sales     60000
3     104  Kiran          IT     70000

In [ ]:
data.tail()

       ID   Name  Department    Salary
0     101  Rahul          IT     50000
1     102  Anita          HR     40000
2     103   Raju       Sales     60000
3     104  Kiran          IT     70000

In [ ]:
data.describe()

               ID        Salary
count    4.000000      4.000000
mean   102.500000  55000.000000
std      1.290994  12909.944487
min    101.000000  40000.000000
25%    101.750000  47500.000000
50%    102.500000  55000.000000
75%    103.250000  62500.000000
max    104.000000  70000.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0       ID      4 non-null      int64
 1     Name      4 non-null      object
 2   Department  4 non-null      object
 3     Salary    4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
import pandas as pd
employee={
    'ID':[101,102,103,104],
    'Name':['Rahul','Ankita','Amar','kavana'],
    'Department':['IT','HR','Sales','IT'],
    'Salary':[50000,18000,210000,22000]
}
df=pd.DataFrame(employee)
df

    ID    Name Department  Salary
0  101   Rahul         IT   50000
1  102  Ankita         HR   18000
2  103    Amar      Sales  210000
3  104  kavana         IT   22000

In [ ]:
print(df['Salary'].mean)

<bound method Series.mean of 0     50000
1     18000
2    210000
3     22000
Name: Salary, dtype: int64>

In [ ]:
print(df[df['Department']=='IT'])

    ID    Name Department  Salary
0  101   Rahul         IT   50000
3  104  kavana         IT   22000

In [ ]:
import pandas as pd
data=pd.read_excel("/content/Emp.xlxxdetails.xlsx")
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,NaN,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data.isnull()

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,True,False
3,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False
8,False,True,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Employee_ID      1
  Name           1
   Age           2
 Gender          1
Department       0
  Salary         0
   CIty          1
Joining -date    0
dtype: int64

In [ ]:
data.isnull().sum().sum

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data['Department']=data['Department'].str.strip()
data

,Employee_ID,Name,Age,Gender,Department,Salary,CIty,Joining -date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chenni,2022-02-15
2,E103,John,28.0,Male,Finance,55000,NaN,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chenni,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hydrabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chenni,2024-01-05

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(0)